<?php

declare(strict_types=1);

namespace App\Tenants\Modules\Ecommerce\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Tenant\EcomCart;
use App\Models\Tenant\EcomCartItem;
use App\Tenants\Modules\Ecommerce\Resources\CartResource;
use App\Tenants\Modules\Ecommerce\Services\CartService;
use DomainException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/**
 * Storefront cart. Authenticated shoppers operate on their own active cart;
 * guests pass a stable `session_token` (anonymous UUID cookie generated by
 * the storefront SPA) to scope the cart.
 */
class CartController extends Controller
{
    public function __construct(private readonly CartService $carts)
    {
    }

    public function show(Request $request): CartResource
    {
        return new CartResource($this->resolveCart($request)->load(['items.product', 'items.variant', 'items.reservation']));
    }

    public function addItem(Request $request): CartResource|JsonResponse
    {
        $data = $request->validate([
            'product_id' => 'required|exists:products,id',
            'variant_id' => 'sometimes|nullable|exists:product_variants,id',
            'quantity' => 'sometimes|numeric|min:0.01|max:9999',
        ]);

        $cart = $this->resolveCart($request);

        try {
            $this->carts->addItem($cart, $data);
        } catch (DomainException $e) {
            return response()->json(['message' => $e->getMessage()], 422);
        }

        return new CartResource($cart->fresh(['items.product', 'items.variant', 'items.reservation']));
    }

    public function updateItem(Request $request, EcomCartItem $item): CartResource|JsonResponse
    {
        $data = $request->validate([
            'quantity' => 'required|numeric|min:0.01|max:9999',
        ]);
        $this->assertItemBelongsToCart($request, $item);

        try {
            $this->carts->updateItemQuantity($item, (float) $data['quantity']);
        } catch (DomainException $e) {
            return response()->json(['message' => $e->getMessage()], 422);
        }

        return new CartResource($item->cart->fresh(['items.product', 'items.variant', 'items.reservation']));
    }

    public function removeItem(Request $request, EcomCartItem $item): CartResource|JsonResponse
    {
        $this->assertItemBelongsToCart($request, $item);
        $cart = $item->cart;

        $this->carts->removeItem($item);

        return new CartResource($cart->fresh(['items.product', 'items.variant', 'items.reservation']));
    }

    private function resolveCart(Request $request): EcomCart
    {
        $customer = Auth::guard('shop')->user();
        if ($customer) {
            return $this->carts->getOrCreateForCustomer($customer);
        }
        $sessionToken = $request->header('X-Cart-Session', $request->input('session_token'));
        if (!is_string($sessionToken) || $sessionToken === '') {
            abort(401, 'Provide X-Cart-Session header or log in.');
        }
        return $this->carts->getOrCreateForGuest($sessionToken);
    }

    private function assertItemBelongsToCart(Request $request, EcomCartItem $item): void
    {
        $cart = $this->resolveCart($request);
        if ($item->cart_id !== $cart->id) {
            abort(403, 'Cart item does not belong to your active cart.');
        }
    }
}
