<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * HRM Phase 8 — Digital Offer & Onboarding Pipeline.
 *
 * `offers` carries the binding job-offer terms tied to a hired Application.
 * Salary / signing bonus are stored as Laravel-`encrypted` text columns
 * (same dual-layer pattern as `employees.base_salary`) so a leaked DB dump
 * still hides compensation. eSignature provider state lives in
 * `esign_envelope_id` + `esign_payload` (jsonb) so we can swap DocuSign for
 * another provider without a schema change.
 *
 * `onboarding_checklists` + `onboarding_tasks` mint the IT / HR / Finance
 * provisioning todo list when an Offer flips to `accepted`. Each task
 * targets a role (`owner_role`) rather than a specific user so a tenant can
 * change the IT lead without re-seeding history.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (!Schema::hasTable('offers')) {
            Schema::create('offers', function (Blueprint $table) {
                $table->uuid('id')->primary();
                $table->uuid('application_id'); // → applications (the hired candidate row)
                $table->uuid('employee_id')->nullable(); // populated on accept via RecruitmentService::convertToEmployee

                $table->string('reference_number', 60)->nullable(); // OFR-YYYYMM-NNN — generated by service
                $table->string('title', 160); // human label e.g. "Senior Engineer - Berlin"
                $table->date('effective_date'); // start date
                $table->date('expires_at')->nullable(); // null = no auto-expire; service compares against now()

                // Compensation — encrypted at rest. Service applies Laravel
                // 'encrypted' cast on the model so query strings are
                // ciphertext too.
                $table->text('base_salary')->nullable();
                $table->text('signing_bonus')->nullable();
                $table->string('currency', 8)->default('USD');
                $table->unsignedSmallInteger('probation_months')->default(3);

                // FSM: draft -> sent -> accepted | declined | expired.
                // Authoritative status set is the `hrm.offer` workflow_statuses
                // module; this column is just the persisted state.
                $table->string('status', 40)->default('draft');

                // eSignature integration — provider-agnostic.
                $table->string('esign_provider', 40)->nullable(); // 'docusign' | 'mock' | ...
                $table->string('esign_envelope_id', 120)->nullable(); // provider-issued envelope ID
                $table->jsonb('esign_payload')->nullable(); // raw webhook bodies kept for audit

                $table->timestamp('sent_at')->nullable();
                $table->timestamp('signed_at')->nullable(); // candidate signature timestamp
                $table->timestamp('declined_at')->nullable();
                $table->text('decline_reason')->nullable();

                $table->text('notes')->nullable(); // recruiter-only annotation

                $table->string('tenant_id');
                $table->timestamps();
                $table->softDeletes();

                $table->index('tenant_id');
                $table->index('status');
                $table->index(['application_id', 'status']);
                $table->unique(['tenant_id', 'reference_number']);
                $table->foreign('application_id')->references('id')->on('applications')->onDelete('cascade');
                $table->foreign('employee_id')->references('id')->on('employees')->onDelete('set null');
            });
        }

        if (!Schema::hasTable('onboarding_checklists')) {
            Schema::create('onboarding_checklists', function (Blueprint $table) {
                $table->uuid('id')->primary();
                $table->uuid('offer_id')->nullable(); // null = checklist created ad-hoc, not from an offer
                $table->uuid('employee_id')->nullable(); // resolved once the Employee row exists

                $table->string('name', 160); // "Default onboarding", "Senior Eng onboarding", ...
                $table->string('status', 40)->default('pending'); // pending | in_progress | completed | cancelled
                $table->unsignedSmallInteger('total_tasks')->default(0);
                $table->unsignedSmallInteger('completed_tasks')->default(0);

                $table->date('target_completion_date')->nullable();
                $table->timestamp('completed_at')->nullable();

                $table->string('tenant_id');
                $table->timestamps();
                $table->softDeletes();

                $table->index('tenant_id');
                $table->index('status');
                $table->index('offer_id');
                $table->index('employee_id');
                $table->foreign('offer_id')->references('id')->on('offers')->onDelete('cascade');
                $table->foreign('employee_id')->references('id')->on('employees')->onDelete('set null');
            });
        }

        if (!Schema::hasTable('onboarding_tasks')) {
            Schema::create('onboarding_tasks', function (Blueprint $table) {
                $table->uuid('id')->primary();
                $table->uuid('checklist_id');

                $table->string('title', 200);
                $table->text('description')->nullable();
                // Role-keyed ownership so a tenant can re-assign IT/HR/Finance
                // leads without rewriting historical task rows. Service layer
                // resolves the role -> user(s) at runtime.
                $table->string('owner_role', 40)->default('hr'); // hr | it | finance | manager | facilities | other
                $table->uuid('owner_user_id')->nullable(); // explicit assignee override

                // Days from `effective_date` until the task should land:
                //   negative = before start (e.g. send laptop two days early),
                //   zero     = day one,
                //   positive = after start.
                $table->smallInteger('due_offset_days')->default(0);
                $table->date('due_date')->nullable(); // computed by service on seed

                $table->string('status', 40)->default('pending'); // pending | in_progress | completed | skipped
                $table->unsignedTinyInteger('sort_order')->default(0);

                $table->timestamp('completed_at')->nullable();
                $table->uuid('completed_by_user_id')->nullable();
                $table->text('completion_notes')->nullable();

                $table->string('tenant_id');
                $table->timestamps();
                $table->softDeletes();

                $table->index('tenant_id');
                $table->index(['checklist_id', 'sort_order']);
                $table->index(['status', 'due_date']);
                $table->index('owner_role');
                $table->foreign('checklist_id')->references('id')->on('onboarding_checklists')->onDelete('cascade');
            });
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('onboarding_tasks');
        Schema::dropIfExists('onboarding_checklists');
        Schema::dropIfExists('offers');
    }
};
